[build]
  functions = "functions"
  publish = "dist"

[dev]
  command = "vite preview --host --port 8888"
  publish = "dist"
  functions = "functions"
  targetPort = 8888
  port = 3000
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/*"